services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: un_tab_p
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33060:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -p'myrootpassword'"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s

  web:
    build: .
    command: python un_tab_p/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: un_tab_p.settings

volumes:
  db_data:
